apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-order-processing-received-binding
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
  - name: queueName
    value: "aws-order-processing-received"
  - name: region
    value: "eu-central-1"
  - name: accessKey
    value: ""
  - name: secretKey
    value: ""
  - name: direction 
    value: "input, output"