apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-order-processing-received-binding
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString # Required when not using Azure Authentication.
    value: ""
  - name: queueName
    value: "omr-order-processing-received"